# Generated by Django 3.2 on 2024-04-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdescription',
            old_name='user_id',
            new_name='username',
        ),
    ]
